name: Primeiro Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Saudacoes
        run: echo "Ola"
      - name: Terminou
        run: echo "Acabou"
